### ISSUE TITLE
Gallio exception with visual studio 2015

### ISSUE THREAD

**Issue by bobbyislam** [Gallio/mbunit-v3#6]
A fatal exception occurred while exploring tests.  Possible causes include invalid test runner parameters.
Gallio.Model.ModelException: An exception occurred while invoking a test driver. ---> System.Runtime.Serialization.SerializationException: Type 'Microsoft.Cci.Pdb.PdbDebugException' in Assembly 'Gallio, Version=3.4.0.0, Culture=neutral, PublicKeyToken=eb9cfa67ee6ab36e' is not marked as serializable.
HResult: -2146233076

Server stack trace: 
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Runtime.Remoting.Channels.BinaryServerFormatterSink.SerializeResponse(IServerResponseChannelSinkStack sinkStack, IMessage msg, ITransportHeaders& headers, Stream& stream)
   at System.Runtime.Remoting.Channels.BinaryServerFormatterSink.ProcessMessage(IServerChannelSinkStack sinkStack, IMessage requestMsg, ITransportHeaders requestHeaders, Stream requestStream, IMessage& responseMsg, ITransportHeaders& responseHeaders, Stream& responseStream)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Gallio.Model.Isolation.HostedTestIsolationContext.RunIsolatedTaskDelegate.EndInvoke(IAsyncResult result)
   at Gallio.Model.Isolation.HostedTestIsolationContext.RunIsolatedTaskInHost[TIsolatedTask](HostSetup hostSetup, StatusReporter statusReporter, Object[] args) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\Isolation\HostedTestIsolationContext.cs:line 127
   at Gallio.Model.Isolation.HostedTestIsolationContext.RunIsolatedTaskImpl[TIsolatedTask](HostSetup hostSetup, StatusReporter statusReporter, Object[] args) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\Isolation\HostedTestIsolationContext.cs:line 83
   at Gallio.Model.DotNetTestDriver.ExploreOrRunAssembly(ITestIsolationContext testIsolationContext, TestPackage testPackage, TestExplorationOptions testExplorationOptions, TestExecutionOptions testExecutionOptions, RemoteMessageSink remoteMessageSink, IProgressMonitor progressMonitor, String taskName, FileInfo file) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\DotNetTestDriver.cs:line 195
   at Gallio.Model.DotNetTestDriver.ExploreOrRun(ITestIsolationContext testIsolationContext, TestPackage testPackage, TestExplorationOptions testExplorationOptions, TestExecutionOptions testExecutionOptions, IMessageSink messageSink, IProgressMonitor progressMonitor, String taskName) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\DotNetTestDriver.cs:line 156
   at Gallio.Model.DotNetTestDriver.ExploreImpl(ITestIsolationContext testIsolationContext, TestPackage testPackage, TestExplorationOptions testExplorationOptions, IMessageSink messageSink, IProgressMonitor progressMonitor) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\DotNetTestDriver.cs:line 141
   at Gallio.Model.DefaultTestFrameworkManager.FilteredTestDriver.<>c__DisplayClass1b.<ExploreImpl>b__19(ITestDriver driver, IList`1 items, Int32 driverCount) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\DefaultTestFrameworkManager.cs:line 446
   at Gallio.Model.DefaultTestFrameworkManager.FilteredTestDriver.ForEachDriver[T](MultiMap`2 testFrameworkPartitions, Func`4 func) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\DefaultTestFrameworkManager.cs:line 528
   --- End of inner exception stack trace ---
HResult: -2146233088
   at Gallio.Model.DefaultTestFrameworkManager.FilteredTestDriver.ForEachDriver[T](MultiMap`2 testFrameworkPartitions, Func`4 func) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\DefaultTestFrameworkManager.cs:line 534
   at Gallio.Model.DefaultTestFrameworkManager.FilteredTestDriver.ExploreImpl(ITestIsolationContext testIsolationContext, TestPackage testPackage, TestExplorationOptions testExplorationOptions, IMessageSink messageSink, IProgressMonitor progressMonitor) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Model\DefaultTestFrameworkManager.cs:line 439
   at Gallio.Runner.DefaultTestRunner.Explore(TestPackage testPackage, TestExplorationOptions testExplorationOptions, IProgressMonitor progressMonitor) in c:\Server\Projects\MbUnit v3\Work\src\Gallio\Gallio\Runner\DefaultTestRunner.cs:line 242

**Comment by aharrim** [comment]
I got the same issue ! 
Is Gallio Icarus  running (Supporting) on Visual Enterprise 2015 ?

Thanks,

**Comment by gas421** [comment]
Hello, actually I have the same issue with VS2015 and Gallio.
Will Gallio will support it?
Thanks

**Comment by seanamos** [comment]
Also experiencing this with our projects that use MBUnit

**Comment by gas421** [comment]
It will be supported?

**Comment by gesmaks** [comment]
I am experiencing the same issue when running tests on Gallio Icarus 3.4 build 11. The test assembly was built using Visual Studio 2015 Professional. The tests worked fine when the test assembly was built using VS 2013.

**Comment by gas421** [comment]
This project I guess is discontinued... so sad....

**Comment by radekpribyl** [comment]
I found a workaround - I installed msbuild v12 (2013) and when I build the test project using this version of mbuild I'm able to run it from Gallio Icarus. When I built it from VS2015 using msbuild v14 I had the same error as described here

**Comment by gesmaks** [comment]
The workaround provided by @radekpribyl works for me. Thank you very much!

**Comment by Subanki** [comment]
Hi all,
Any help with the below stuff is much appreciated.
I really need some support on How Can I run my MBunit tests in Gallio Echo. I have my MBunit tests in VS2013. I could add the test.dll in Gallio Icarus and run it manually. But I would like to do it from command line using gallio echo. I am not sure how to start with this.

I have my test.dll in this path in my local machine "C:\Users\suba\Documents\Visual Studio 2013\Projects\Links\Links\bin\Debug\Tests.dll"

I have my Gallio.Echo.Exe installed in this path "C:\Gallio\bin"

I know the command to run tests.dll is 'Gallio.Echo Tests.dll'
I don't know from which path and what command to use to run my test.dll in command line

Should we need anything else that needs to be specified within my test code. Please guide with this.

**Comment by ssg** [comment]
I worked on this today. The problem was that the `Microsoft.Cci.Metadata` library which was used in Gallio 3.4 did not support the new PDB files generated by VS2015, (it fails with "unknown metadata code 7" exception). Because the library code was embedded in the assembly (or some other magic I'm not aware of), updating to new DLL's was not possible. I got Gallio build on VS2015, get an updated Microsoft.Cci.Metadata build (no binary distributions exist), made the build work half-assed. The final problem is that assembly versions show up as 0.0.0.0 and that causes problems with the test runner. Feel free to clone from https://github.com/ssg/mbunit-v3 and hack away. I will update this thread if I get to make it work perfectly.

**Comment by aprajitamathur** [comment]
The workaround  by @radekpribyl worked for me as well . Thank you !

**Comment by awalsh128** [comment]
To those using the suggestion from @radekpribyl . Understand this isn't a workaround, it is just rolling back to the SDK that already works with MbUnit. You still lose the features introduced in the newer SDK that came with VS2015.

**Comment by ssg** [comment]
I gave up and switched to NUnit fyi. https://gist.github.com/ssg/5329684

**Comment by awalsh128** [comment]
Same boat as you. NUnit has active dev and the easiest migration path from MbUnit. Thanks for providing the cheat sheet.

**Comment by j9brown** [comment]
_sigh_

**Comment by tgiphil** [comment]
We switched to xunit:

https://github.com/xunit/xunit
http://xunit.github.io/

**Comment by Sharkhayn** [comment]
Hello I try use the @radekpribyl solution, but I don't know how.

Where do I specify the msbuild version for a local build ?

cc @gesmaks @aprajitamathur

Thanks.
